# Generated by Django 3.1.5 on 2021-01-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='worked_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.employee'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.employee'),
        ),
    ]
